language: python
python:
  - "3.7"
# command to install dependencies
install:
  - sudo apt install python3-pyqt5 || pip3 install pyqt5
  - pip3 install -r requirements.txt
# command to run tests
script:
  - sudo python3 GScanner.py || python3 GScanner.py